/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_juanlopez;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author jjlm1
 */
public class Boroa extends javax.swing.JFrame {

    /**
     * Creates new form Boroa
     */
    public Boroa() {
        initComponents();
        this.setVisible(false);
        jf_carros.pack();
        jf_carros.setLocationRelativeTo(this);
        jf_carrera.pack();
        jf_carrera.setLocationRelativeTo(this);
        jf_carros.setVisible(true);
        File archivo =new File("./AnyConv.com__Rick Astley - Never Gonna Give You Up (Official Music Video)(MP3_160K).wav");
        try {
            AudioInputStream aud= AudioSystem.getAudioInputStream(archivo);
            Clip clip;
            try {
                clip = AudioSystem.getClip();
                clip.open(aud);
                clip.start();
                clip.loop(-1);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Boroa.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(Boroa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Boroa.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultComboBoxModel cb1=(DefaultComboBoxModel)cb_carros1.getModel();
        cb1.removeAllElements();
        ac.cargar();
        for (int i = 0; i < ac.getCarros().size(); i++) {
            cb1.addElement(ac.getCarros().get(i));
        }
        cb_carros1.setModel(cb1);
        DefaultComboBoxModel cb2=(DefaultComboBoxModel)cb_carros2.getModel();
        cb2.removeAllElements();
        for (int i = 0; i < ac.getCarros().size(); i++) {
            cb2.addElement(ac.getCarros().get(i));
        }
        cb_carros2.setModel(cb2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_carros = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        cb_carros2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jl_modelo = new javax.swing.JLabel();
        jl_vel = new javax.swing.JLabel();
        jl_marca = new javax.swing.JLabel();
        jl_modelo1 = new javax.swing.JLabel();
        jl_vel1 = new javax.swing.JLabel();
        jl_marca1 = new javax.swing.JLabel();
        bt_optimus = new javax.swing.JButton();
        cb_carros1 = new javax.swing.JComboBox<>();
        bt_cerrar = new javax.swing.JButton();
        bt_crear3 = new javax.swing.JButton();
        jf_carrera = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jl_carro2 = new javax.swing.JLabel();
        jl_carro1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bt_crear = new javax.swing.JButton();
        bt_crear2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        js_vel = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_modelo = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102), 5));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_carros2.setBackground(new java.awt.Color(102, 0, 102));
        cb_carros2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        cb_carros2.setForeground(new java.awt.Color(255, 255, 255));
        cb_carros2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_carros2ItemStateChanged(evt);
            }
        });
        jPanel6.add(cb_carros2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("vs");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("¡¡A correr!!");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel8.setText("Modelo");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel9.setText("Velocidad");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setText("Marca");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel11.setText("Modelo");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel12.setText("Velocidad");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel13.setText("Marca");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jl_modelo.setText("                                               ");
        jPanel6.add(jl_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jl_vel.setText("                                               ");
        jPanel6.add(jl_vel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jl_marca.setText("                                               ");
        jPanel6.add(jl_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jl_modelo1.setText("                                               ");
        jPanel6.add(jl_modelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        jl_vel1.setText("                                               ");
        jPanel6.add(jl_vel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jl_marca1.setText("                                               ");
        jPanel6.add(jl_marca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        bt_optimus.setBackground(new java.awt.Color(102, 0, 102));
        bt_optimus.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        bt_optimus.setForeground(new java.awt.Color(255, 255, 255));
        bt_optimus.setText("A rodar >:D");
        bt_optimus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(51, 0, 51)));
        bt_optimus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_optimusActionPerformed(evt);
            }
        });
        jPanel6.add(bt_optimus, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 340, 230, 40));

        cb_carros1.setBackground(new java.awt.Color(102, 0, 102));
        cb_carros1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        cb_carros1.setForeground(new java.awt.Color(255, 255, 255));
        cb_carros1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_carros1ItemStateChanged(evt);
            }
        });
        jPanel6.add(cb_carros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 170, -1));

        bt_cerrar.setBackground(new java.awt.Color(204, 0, 0));
        bt_cerrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_cerrar.setText("Finalizar ");
        bt_cerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarActionPerformed(evt);
            }
        });
        jPanel6.add(bt_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        bt_crear3.setBackground(new java.awt.Color(204, 0, 102));
        bt_crear3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_crear3.setText("Crear Carro");
        bt_crear3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        bt_crear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear3ActionPerformed(evt);
            }
        });
        jPanel6.add(bt_crear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 10, 120, 30));

        javax.swing.GroupLayout jf_carrosLayout = new javax.swing.GroupLayout(jf_carros.getContentPane());
        jf_carros.getContentPane().setLayout(jf_carrosLayout);
        jf_carrosLayout.setHorizontalGroup(
            jf_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        jf_carrosLayout.setVerticalGroup(
            jf_carrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 5));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tiempo");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 255, 102));
        jLabel15.setText("00:00");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel16.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("PROGRESO");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        jl_carro2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jl_carro2.setText("                         ");
        jPanel7.add(jl_carro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jl_carro1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jl_carro1.setText("                     ");
        jPanel7.add(jl_carro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        jPanel7.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 290, 30));
        jPanel7.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, 30));

        javax.swing.GroupLayout jf_carreraLayout = new javax.swing.GroupLayout(jf_carrera.getContentPane());
        jf_carrera.getContentPane().setLayout(jf_carreraLayout);
        jf_carreraLayout.setHorizontalGroup(
            jf_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jf_carreraLayout.setVerticalGroup(
            jf_carreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        bt_crear.setBackground(new java.awt.Color(204, 0, 102));
        bt_crear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_crear.setText("Crear");
        bt_crear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        bt_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearActionPerformed(evt);
            }
        });

        bt_crear2.setBackground(new java.awt.Color(204, 0, 102));
        bt_crear2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_crear2.setText("Correr");
        bt_crear2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        bt_crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crear2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(bt_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(bt_crear2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_crear, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(bt_crear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, 30));

        jPanel3.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        jPanel4.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 10, 270));

        jPanel5.setBackground(new java.awt.Color(102, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CREACIÓN DE CARROS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel2.setText("km/h");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 80, -1));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel3.setText("Marca");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));

        js_vel.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel1.add(js_vel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, -1));

        jLabel4.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel4.setText("Modelo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 60, -1));

        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel5.setText("Velocidad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, -1));
        jPanel1.add(tf_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 170, -1));
        jPanel1.add(tf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crearActionPerformed
        // TODO add your handling code here:
        String marca=tf_marca.getText();
        String modelo=tf_modelo.getText();
        int velocidad=(Integer)js_vel.getValue();
        Carro c=new Carro(marca, modelo, velocidad);
        ac.cargar();
        ac.agregarCarro(c);
        ac.escribir();
        DefaultComboBoxModel cb1=(DefaultComboBoxModel)cb_carros1.getModel();
        cb1.removeAllElements();
        ac.cargar();
        for (int i = 0; i < ac.getCarros().size(); i++) {
            cb1.addElement(ac.getCarros().get(i));
        }
        cb_carros1.setModel(cb1);
        DefaultComboBoxModel cb2=(DefaultComboBoxModel)cb_carros2.getModel();
        cb2.removeAllElements();
        for (int i = 0; i < ac.getCarros().size(); i++) {
            cb2.addElement(ac.getCarros().get(i));
        }
        cb_carros2.setModel(cb2);
        tf_marca.setText("");
        tf_modelo.setText("");
        js_vel.setValue(1);
    }//GEN-LAST:event_bt_crearActionPerformed

    private void bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_bt_cerrarActionPerformed

    private void bt_crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear2ActionPerformed
        // TODO add your handling code here:
        jf_carros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_crear2ActionPerformed

    private void bt_crear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_crear3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_bt_crear3ActionPerformed

    private void cb_carros1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_carros1ItemStateChanged
        // TODO add your handling code here:
        try{
        Carro c1=(Carro) cb_carros1.getSelectedItem();
        jl_marca.setText(c1.getMarca());
        jl_modelo.setText(c1.getModelo());
        jl_vel.setText(String.valueOf(c1.getVel()));
        } catch(Exception ex){
            
        }
    }//GEN-LAST:event_cb_carros1ItemStateChanged

    private void cb_carros2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_carros2ItemStateChanged
        // TODO add your handling code here:
        try {
            Carro c2=(Carro) cb_carros2.getSelectedItem();
        jl_marca1.setText(c2.getMarca());
        jl_modelo1.setText(c2.getModelo());
        jl_vel1.setText(String.valueOf(c2.getVel()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cb_carros2ItemStateChanged

    private void bt_optimusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_optimusActionPerformed
        // TODO add your handling code here:
        Carro c1=(Carro) cb_carros1.getSelectedItem();
        Carro c2=(Carro) cb_carros2.getSelectedItem();
        jl_carro1.setText(c1.getModelo());
        jl_carro2.setText(c2.getModelo());
    }//GEN-LAST:event_bt_optimusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boroa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boroa().setVisible(false);
            }
        });
    }
AdminCarro ac=new AdminCarro("./hotwheels.jjlm");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cerrar;
    private javax.swing.JButton bt_crear;
    private javax.swing.JButton bt_crear2;
    private javax.swing.JButton bt_crear3;
    private javax.swing.JButton bt_optimus;
    private javax.swing.JComboBox<String> cb_carros1;
    private javax.swing.JComboBox<String> cb_carros2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JFrame jf_carrera;
    private javax.swing.JFrame jf_carros;
    private javax.swing.JLabel jl_carro1;
    private javax.swing.JLabel jl_carro2;
    private javax.swing.JLabel jl_marca;
    private javax.swing.JLabel jl_marca1;
    private javax.swing.JLabel jl_modelo;
    private javax.swing.JLabel jl_modelo1;
    private javax.swing.JLabel jl_vel;
    private javax.swing.JLabel jl_vel1;
    private javax.swing.JSpinner js_vel;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modelo;
    // End of variables declaration//GEN-END:variables
}
